name: Mirror GitHub Pages
# this workflow mirrors the gh-pages branch to my main gh-pages site
on:
  push:
    branches:
      - gh-pages

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - run: echo Hello World